name: Run tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis-version: [ 5,6 ]
        postgres-version: [14, 13]
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - uses: supercharge/redis-github-action@1.2.0
      with:
        redis-version: ${{ matrix.redis-version }}
    - uses: ankane/setup-postgres@v1
      with:
        postgres-version: ${{ matrix.postgres-version }}
    - name: Bundle Install
      run: bundle install --path vendor/bundle --jobs 4 --retry 3
    - name: Yarn Install
      run: bin/rails yarn:install
    - name: Create database
      run: bundle exec rails db:create
    - name: Run migration
      run: bundle exec rails db:migrate
    - name: Run Rails Tests
      run: |
        bundle exec rake


